# Generated by Django 6.0.7 on 2026-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Curso"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "estado",
                    models.BooleanField(default=True, verbose_name="Curso Activo"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
