# Generated by Django 6.0.7 on 2026-08-27 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_inscripcion_material_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_matricula'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Docente Responsable'),
        ),
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/', verbose_name='Archivo Adjunto (PDF, ZIP, etc.)'),
        ),
        migrations.AddField(
            model_name='material',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo (Video, Meet, Drive)'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_inscritos', to='academia.curso'),
        ),
        migrations.AlterField(
            model_name='material',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Instrucciones o Detalles Adicionales'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('CLASE', 'Clase Grabada / Diapositivas'), ('LECTURA', 'Lectura / PDF'), ('EXAMEN', 'Examen / Simulacro'), ('TAREA', 'Tarea Práctica')], default='CLASE', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Material'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Final'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_curso', to='academia.curso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones del Docente'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'curso')},
        ),
    ]
