# Generated by Django 6.0.7 on 2026-08-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
