# Generated by Django 6.0.7 on 2026-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_inscripcion_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='cursos_portadas/'),
        ),
    ]
