# Generated by Django 6.0.7 on 2026-08-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_calificacion_delete_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['semana', '-fecha_subida']},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='enlace',
            new_name='enlace_web',
        ),
        migrations.AddField(
            model_name='material',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Semana / Sesión'),
        ),
    ]
