# Generated by Django 6.0.7 on 2026-08-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alter_material_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Verano 2027, Ciclo Regular 2027-1', max_length=50)),
                ('codigo', models.CharField(help_text='Ej: 2027-0, 2027-1', max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Indica si es el período vigente')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['semana', '-fecha_subida'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='material',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Instrucciones o Detalles Adicionales'),
        ),
        migrations.AddField(
            model_name='material',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo (Video, Meet, Drive)'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('CLASE', 'Clase Grabada / Diapositivas'), ('LECTURA', 'Lectura / PDF'), ('EXAMEN', 'Examen / Simulacro'), ('TAREA', 'Tarea Práctica')], default='CLASE', max_length=50),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota1',
            field=models.FloatField(blank=True, null=True, verbose_name='Examen Parcial'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota2',
            field=models.FloatField(blank=True, null=True, verbose_name='Evaluación Continua'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota3',
            field=models.FloatField(blank=True, null=True, verbose_name='Examen Final'),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/', verbose_name='Archivo Adjunto (PDF, ZIP, etc.)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='enlace_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Web Alternativo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Material'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='academia.periodoacademico'),
        ),
    ]
