# Generated by Django 6.0.7 on 2026-09-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_periodoacademico_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Banner Médico', help_text='Descripción o referencia de la foto', max_length=150)),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo (Horizontal)')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición: 1, 2, 3...')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Banner del Carrusel',
                'verbose_name_plural': 'Banners del Carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='🩺 Especialistas en Formación y Ciencias de la Salud', max_length=120)),
                ('hero_titulo', models.CharField(default='Formando a los Mejores Profesionales de la Salud', max_length=200)),
                ('hero_subtitulo', models.TextField(default='Metodología de alto rendimiento, docentes médicos especializados y resolución de casos reales para potenciar tu nivel académico.')),
                ('sobre_nosotros_titulo', models.CharField(default='Comprometidos con la excelencia y el rigor científico', max_length=200)),
                ('sobre_nosotros_texto_1', models.TextField(default='En Academia Galeno nos dedicamos al fortalecimiento de competencias en estudiantes y profesionales de ciencias de la salud.')),
                ('sobre_nosotros_texto_2', models.TextField(default='Contamos con una infraestructura virtual moderna orientada a la resolución ágil de dudas y a la asimilación profunda de cada asignatura médica.')),
                ('sobre_nosotros_imagen', models.ImageField(blank=True, null=True, upload_to='institucional/', verbose_name='Foto Sobre Nosotros')),
                ('mision', models.TextField(default='Brindar una educación complementaria y de especialización médica accesible, estructurada y exigente que potencie el rendimiento y la capacidad de toma de decisiones clínicas.')),
                ('vision', models.TextField(default='Ser la academia líder de formación y actualización en ciencias médicas a nivel nacional, reconocida por el rigor de sus programas y el éxito de sus egresados.')),
                ('valores', models.TextField(default='Rigor científico, compromiso con la salud humana, integridad profesional, innovación pedagógica constante y vocación de servicio docente.')),
                ('whatsapp_contacto', models.CharField(default='51999999999', help_text='Código de país seguido del número (ej. 51987654321)', max_length=20)),
                ('correo_contacto', models.EmailField(default='informes@academiagaleno.pe', max_length=254)),
                ('horario_atencion', models.CharField(default='Lun - Sáb: 8:00 AM - 8:00 PM', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de la Portada',
                'verbose_name_plural': 'Configuración de la Portada',
            },
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
