# Generated by Django 6.0.7 on 2026-09-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_bannercarrusel_configuracionlanding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('curso_interes', models.CharField(max_length=150)),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Evaluación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Instrucciones')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Tiempo límite en minutos')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible para alumnos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academia.curso')),
            ],
            options={
                'verbose_name': 'Examen / Evaluación',
                'verbose_name_plural': 'Exámenes y Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_examen', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='academia.examen')),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Resultados de Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('explicacion', models.TextField(blank=True, verbose_name='Explicación / Justificación (Feedback médico)')),
                ('puntaje', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Puntaje asignado')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academia.examen')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Banco de Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Opción de Respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='academia.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
    ]
