# Generated by Django 6.0.7 on 2026-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_prospecto_examen_intentoexamen_pregunta_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de la semana en la que aparecerá el examen (Ej: 1, 2, 8)', verbose_name='Semana del Ciclo'),
        ),
    ]
