# Generated by Django 6.0.7 on 2026-09-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0014_examen_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semana donde se mostrará la evaluación', verbose_name='Semana del Ciclo'),
        ),
    ]
