# Generated by Django 6.0.7 on 2026-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_examen_fecha_apertura_examen_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='cantidad_preguntas_aleatorias',
            field=models.PositiveIntegerField(default=0, help_text='0 para mostrar todas las preguntas registradas, o un número (ej. 10) para extraer aleatoriamente solo esa cantidad del banco.'),
        ),
    ]
