# Generated by Django 6.0.7 on 2026-09-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_examen_cantidad_preguntas_aleatorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentoexamen',
            options={},
        ),
        migrations.AddField(
            model_name='examen',
            name='intentos_permitidos',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de veces que un estudiante puede rendir esta prueba.', verbose_name='Intentos Permitidos'),
        ),
        migrations.AlterField(
            model_name='intentoexamen',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academia.intentoexamen')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
            },
        ),
    ]
