# Generated by Django 6.0.7 on 2026-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_alter_intentoexamen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='cerrado_manualmente',
            field=models.BooleanField(default=False, help_text='Si está activo, fuerza el autoenvío de las evaluaciones en curso.', verbose_name='Cerrado Manualmente por Docente'),
        ),
    ]
