# Generated by Django 6.0.7 on 2026-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_examen_cerrado_manualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='etiqueta_n1',
            field=models.CharField(default='Nota 1 (Teoría)', max_length=50, verbose_name='Etiqueta N1'),
        ),
        migrations.AddField(
            model_name='curso',
            name='etiqueta_n2',
            field=models.CharField(default='Nota 2 (Práctica)', max_length=50, verbose_name='Etiqueta N2'),
        ),
        migrations.AddField(
            model_name='curso',
            name='etiqueta_n3',
            field=models.CharField(default='Nota 3 (Examen Final)', max_length=50, verbose_name='Etiqueta N3'),
        ),
        migrations.AddField(
            model_name='curso',
            name='formula_evaluacion',
            field=models.CharField(default='(N1 + N2 + N3) / 3', help_text='Usa las variables N1, N2, N3. Ejemplo: (N1*0.2) + (N2*0.3) + (N3*0.5)', max_length=255, verbose_name='Fórmula de Promedio'),
        ),
    ]
