# Generated by Django 6.0.7 on 2026-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_curso_etiqueta_n1_curso_etiqueta_n2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='etiqueta_n1',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='etiqueta_n2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='etiqueta_n3',
        ),
        migrations.AddField(
            model_name='curso',
            name='criterios_evaluacion',
            field=models.JSONField(blank=True, default=list, verbose_name='Criterios y Columnas de Evaluación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='formula_evaluacion',
            field=models.CharField(default='(N1 + N2 + N3) / 3', help_text='Usa las variables N1, N2, N3, N4... Ejemplo: (N1*0.2) + (N2*0.3) + (N3*0.5)', max_length=255, verbose_name='Fórmula de Promedio'),
        ),
    ]
