# Generated by Django 6.0.7 on 2026-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_horariocurso_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'semana'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='intentoexamen',
            options={'verbose_name': 'Intento de Examen', 'verbose_name_plural': 'Resultados de Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='prospecto',
            options={'verbose_name': 'Prospecto', 'verbose_name_plural': 'Prospectos'},
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota3',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='semana',
            field=models.PositiveIntegerField(default=1, verbose_name='Semana del Ciclo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='notas_detalle',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalle de Notas'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio Final'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cantidad_preguntas_aleatorias',
            field=models.PositiveIntegerField(default=0, help_text='0 para mostrar todas las preguntas registradas, o un número para extraer aleatoriamente solo esa cantidad.'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cerrado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Cerrado Manualmente por Docente'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='intentos_permitidos',
            field=models.PositiveIntegerField(default=1, verbose_name='Intentos Permitidos'),
        ),
    ]
