# Generated by Django 6.0.7 on 2026-09-09 06:29

import academia.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0022_alter_asistencia_options_alter_intentoexamen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.RemoveField(
            model_name='material',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='material',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace del video (Vimeo, YouTube sin listar o Bunny Stream)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/', validators=[academia.validators.validar_archivo_material]),
        ),
        migrations.AlterField(
            model_name='material',
            name='enlace_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='semana',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
