# Generated by Django 6.0.7 on 2026-09-12 03:39

import academia.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0023_alter_material_options_remove_material_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['semana', '-fecha_subida'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='material',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Instrucciones o Detalles Adicionales'),
        ),
        migrations.AddField(
            model_name='material',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo (Drive, Meet)'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('CLASE', 'Clase Grabada / Diapositivas'), ('LECTURA', 'Lectura / PDF'), ('EXAMEN', 'Examen / Simulacro'), ('TAREA', 'Tarea Práctica')], default='CLASE', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/', validators=[academia.validators.validar_archivo_material], verbose_name='Archivo Adjunto (PDF, ZIP, etc.)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='enlace_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Web Alternativo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Semana / Sesión'),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace del video (Vimeo, YouTube o Bunny Stream)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='GrupoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Grupo 1, Grupo A, Sección A', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academia.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Curso',
                'verbose_name_plural': 'Grupos de Cursos',
                'unique_together': {('curso', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academia.grupocurso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_inscritos', to='academia.grupocurso'),
        ),
    ]
